// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SteamWebAPI2.Models
{
    public class BadgeQuest
    {
        [JsonProperty("questid")]
        public int QuestId { get; set; }

        [JsonProperty("completed")]
        public bool Completed { get; set; }
    }

    public class CommunityBadgeProgressResult
    {
        [JsonProperty("quests")]
        public IList<BadgeQuest> Quests { get; set; }
    }

    public class CommunityBadgeProgressResultContainer
    {
        [JsonProperty("response")]
        public CommunityBadgeProgressResult Result { get; set; }
    }
}