// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SteamWebAPI2.Models
{
    public class PlayingSharedGameResult
    {
        [JsonProperty("lender_steamid")]
        public string LenderSteamId { get; set; }
    }

    public class PlayingSharedGameResultContainer
    {
        [JsonProperty("response")]
        public PlayingSharedGameResult Result { get; set; }
    }
}