// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SteamWebAPI2.Models
{
    public class ResolveVanityUrlResult
    {
        [JsonProperty("steamid")]
        public long SteamId { get; set; }

        [JsonProperty("success")]
        public int Success { get; set; }
    }

    public class ResolveVanityUrlResultContainer
    {
        [JsonProperty("response")]
        public ResolveVanityUrlResult Result { get; set; }
    }
}