// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SteamWebAPI2.Models
{
    public class SteamApp
    {
        [JsonProperty("appid")]
        public int AppId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public class SteamAppList
    {
        [JsonProperty("app")]
        public IList<SteamApp> Apps { get; set; }
    }

    public class SteamAppListResult
    {
        [JsonProperty("apps")]
        public SteamAppList AppList { get; set; }
    }

    public class SteamAppListResultContainer
    {
        [JsonProperty("applist")]
        public SteamAppListResult AppListResult { get; set; }
    }
}