// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SteamWebAPI2.Models
{
    public class UserStat
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("value")]
        public int Value { get; set; }
    }

    public class UserStatAchievement
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("achieved")]
        public int Achieved { get; set; }
    }

    public class UserStatsForGameResult
    {
        [JsonProperty("steamID")]
        public string SteamId { get; set; }

        [JsonProperty("gameName")]
        public string GameName { get; set; }

        [JsonProperty("stats")]
        public IList<UserStat> Stats { get; set; }

        [JsonProperty("achievements")]
        public IList<UserStatAchievement> Achievements { get; set; }
    }

    internal class UserStatsForGameResultContainer
    {
        [JsonProperty("playerstats")]
        public UserStatsForGameResult Result { get; set; }
    }
}