// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SteamWebAPI2.Models.GameEconomy
{
    public class SchemaUrlResult
    {
        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("items_game_url")]
        public string ItemsGameUrl { get; set; }
    }

    public class SchemaUrlResultContainer
    {
        [JsonProperty("result")]
        public SchemaUrlResult Result { get; set; }
    }
}