// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using SteamWebAPI2.Utilities.JsonConverters;
using System;
using System.Collections.Generic;

namespace SteamWebAPI2.Models.TF2
{
    public class GoldenWrench
    {
        [JsonProperty("steamID")]
        public object SteamId { get; set; }

        [JsonConverter(typeof(UnixTimeJsonConverter))]
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; }

        [JsonProperty("itemID")]
        public int ItemId { get; set; }

        [JsonProperty("wrenchNumber")]
        public int WrenchNumber { get; set; }
    }

    public class GoldenWrenchResult
    {
        [JsonProperty("wrenches")]
        public IList<GoldenWrench> GoldenWrenches { get; set; }
    }

    internal class GoldenWrenchResultContainer
    {
        [JsonProperty("results")]
        public GoldenWrenchResult Result { get; set; }
    }
}