// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;

namespace SteamWebAPI2.Models.SteamCommunity
{
    public class GlobalAchievementPercentage
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("percent")]
        public double Percent { get; set; }
    }

    public class GlobalAchievementPercentagesResult
    {
        [JsonProperty("achievements")]
        public IList<GlobalAchievementPercentage> AchievementPercentages { get; set; }
    }

    public class GlobalAchievementPercentagesResultContainer
    {
        [JsonProperty("achievementpercentages")]
        public GlobalAchievementPercentagesResult Result { get; set; }
    }
}