// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SteamWebAPI2.Models.SteamPlayer
{
    public class CurrentPlayersResult
    {
        [JsonProperty("player_count")]
        public int PlayerCount { get; set; }

        [JsonProperty("result")]
        public int Result { get; set; }
    }

    public class CurrentPlayersResultContainer
    {
        [JsonProperty("response")]
        public CurrentPlayersResult Result { get; set; }
    }
}