// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using SteamWebAPI2.Utilities.JsonConverters;
using System;
using System.Collections.Generic;

namespace SteamWebAPI2.Models.SteamCommunity
{
    public class Friend
    {
        [JsonProperty("steamid")]
        public string SteamId { get; set; }

        [JsonProperty("relationship")]
        public string Relationship { get; set; }

        [JsonProperty("friend_since")]
        [JsonConverter(typeof(UnixTimeJsonConverter))]
        public DateTime FriendSince { get; set; }
    }

    public class FriendsList
    {
        [JsonProperty("friends")]
        public IList<Friend> Friends { get; set; }
    }

    internal class FriendsListResultContainer
    {
        [JsonProperty("friendslist")]
        public FriendsList Result { get; set; }
    }
}