// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SteamWebAPI2.Models.SteamCommunity
{
    public class ResolveVanityUrlResult
    {
        [JsonProperty("steamid")]
        public ulong SteamId { get; set; }

        [JsonProperty("success")]
        public int Success { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    internal class ResolveVanityUrlResultContainer
    {
        [JsonProperty("response")]
        public ResolveVanityUrlResult Result { get; set; }
    }
}