// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SteamWebAPI2.Models.SteamCommunity
{
    public class SteamLevelResult
    {
        [JsonProperty("player_level")]
        public int PlayerLevel { get; set; }
    }

    public class SteamLevelResultContainer
    {
        [JsonProperty("response")]
        public SteamLevelResult Result { get; set; }
    }
}